# This workflows uploads a Python Package using Flit when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish

on:
  release:
    types: [published]

jobs:
    publish:
      name: Upload a release to PyPI
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.9
            
        - name: Install Flit
          run: |
              python -m pip install flit

        - name: Build Flit
          run: |
              python -m flit build

        - name: Publish
          env:
            FLIT_USERNAME: __token__
            FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          run: python -m flit publish
